### ISSUE TITLE
Use environment variables 

### ISSUE THREAD

**Issue by kgaut** [foxylion/docker-search-replace-db#1]
Hi,

Thanks for your little image, very usefull :)

I'm using it with docker compose, and I wonder if it would be possible to use environment variable to populate db_host, name, user, password... and maybe even source_url and target url ?

I don't even know if srdb allow it :)

**Comment by foxylion** [comment]
Hi @kgaut,

thanks for suggesting the feature. Feel free and try to add this in a pull request. I'm happy to merge any improvements. 😄

**Comment by foxylion** [comment]
Solved with #2
